name: PandeLoot
main: net.seyarada.pandeloot.PandeLoot
version: dev
api-version: 1.17
softdepend: [MythicMobs, MMOItems]
commands:
  pandeloot:
    description: Base command for PandeLoot
    usage: /pandeloot
    permission: pandeloot.use
    aliases:
      - ploot